### ISSUE TITLE
Could not get a download URL: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by delpech** [haircut/haircut-recipes#1] opened 2019-10-22 09:11 UTC
Hi,

I get the error message "Could not get a download URL: HTTP Error 400: Bad Request" when I use the recipe DaVinciResolve16.pkg.recipe.

This seems to happen when the recipe requests a URL to the registration submission. The information entered in my override recipe works however when I register directly from the Website.

Have you also noticed this problem?

Sylvain

Error message:
BlackMagicURLProvider
BlackMagicURLProvider: Filtering json 'name' attributes with regex ^DaVinci Resolve (?P<version>16(\.\d+)*)( Update)*$
Could not get a download URL: HTTP Error 400: Bad Request
Failed.
Receipt written to /Users/casperadmin/Library/AutoPkg/Cache/local.pkg.DaVinciResolve16-Lab/receipts/DaVinciResolve16-Lab-receipt-20191022-104902.plist

The following recipes failed:
    DaVinciResolve16-Lab.pkg
        Error in local.pkg.DaVinciResolve16-Lab: Processor: BlackMagicURLProvider: Error: Could not get a download URL: HTTP Error 400: Bad Request

Nothing downloaded, packaged or imported.

**Comment by haircut** [comment] 2019-10-22 11:43
@delpech I believe this is a duplicate of https://github.com/autopkg/timsutton-recipes/issues/63 - please comment on that existing issue. The error is in `BlackMagicURLProvider` which is part of the upstream recipe and I do not have control over that – but I'll take a look and send a PR if I can discern the issue!

**Closed by haircut** 2019-10-22 11:43 UTC
